# Generated by Django 6.0 on 2025-12-18 16:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('meter_number', models.CharField(help_text='Serial Number', max_length=50)),
                ('current_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='rent_app.property')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('base_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent_due_date', models.IntegerField(blank=True, default=1, help_text='Day of the month (1-31)', null=True)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('include_electricity', models.BooleanField(default=True)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('is_archived', models.BooleanField(default=False)),
                ('left_date', models.DateField(blank=True, null=True)),
                ('meter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tenant', to='rent_app.meter')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='rent_app.property')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_charges', to='rent_app.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('RENT', 'Rent'), ('ELEC', 'Electricity')], default='RENT', max_length=10)),
                ('mode', models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHECK', 'Check')], default='UPI', max_length=10)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('notes', models.TextField(blank=True)),
                ('meter_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('units_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rent_app.tenant')),
            ],
        ),
    ]
